[tools]
python = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "pip install -r requirements.txt"


[tasks.run]
description = "Run the application"
run = "python polyphonic_markov_chain2.py"
alias = "r"
